task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 1
remap_mscoco_category: True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: D:\Code\RT-DETR-test\raw_dataset\WiSARD_VIS-4\train\
    ann_file: D:\Code\RT-DETR-test\dataset_annotations\train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 1
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: D:\Code\RT-DETR-test\raw_dataset\HERIDAL\test\
    ann_file: D:\Code\RT-DETR-test\dataset_annotations\valid.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 1
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
