use_amp: True
use_ema: True 
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

epoches: 15  # ✅ 二階段只訓練 15 epoch
clip_max_norm: 0.1

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.000005  # ✅ backbone 降低學習率
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lr_scheduler:
  type: MultiStepLR
  milestones: [10]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 2000
