__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include_step2/dataloader.yml',
  './include_step2/optimizer.yml',
  './include_step2/rtdetrv2_r50vd.yml',
]


output_dir: ./output/WiSARD_MOBDRONE_Step2  



# optimizer:
#   type: AdamW
#   params: 
#     - 
#       params: '^(?=.*backbone)(?!.*norm).*$'
#       lr: 0.00001
#     - 
#       params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
#       weight_decay: 0.

#   lr: 0.0001
#   betas: [0.9, 0.999]
#   weight_decay: 0.0001

